name: First workflow 
on: workflow_dispatch
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello world 
        run: |
             echo "asjkdhasjkhd"
             echo "sakjdhksajhdjkashdjk"
             echo "123"