name: First Workflow
on: push
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
       - run: |
              echo "sdasdsad"
              echo "fkjsdhfjksdhfjksdkf"
              echo "sdkjfhsdjkfhsdjkfhsdjkfh"